=== ricardoSlv/DAW2020/T2/project-record.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project-record (project-data,workteam,main-content,deliverables) >

<!ELEMENT project-data (keyname,title,subtitle,begin-date,end-date,supervisor) >
<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin-date (#PCDATA) >
<!ELEMENT end-date (#PCDATA) >
<!ELEMENT supervisor (name,email,url) >

<!ELEMENT workteam (team-member)+ >
<!ELEMENT team-member (name,number,email,url) >

<!ELEMENT email (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT number (#PCDATA) >

<!ELEMENT main-content (abstract) >
<!ELEMENT abstract (p,p,p,p+) >
<!ELEMENT p (#PCDATA|i|b|u|url)* >
<!ELEMENT b (#PCDATA) >
<!ELEMENT i (#PCDATA) >
<!ELEMENT u (#PCDATA) >
<!ELEMENT deliverables (url)+ >



<!ELEMENT url (#PCDATA) >
<!ATTLIST url href CDATA #REQUIRED >

=== ricardoSlv/DAW2020/T4/project-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "../DAWTPC2/project-record.dtd">
<project-record>
    <project-data>
        <keyname>DAW-TPC3-2020</keyname>
        <title>Criação de um ficheiro XSLt para geração de um Website multi-página</title>
        <subtitle>Relatório do trabalho de casa 3 da cadeira DAW 2020</subtitle>
        <begin-date>Outubro 2020</begin-date>
        <end-date>Outubro 2020</end-date>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <email>jcr@di.uminhp.pt</email>
            <url href="http://www3.di.uminho.pt/~jcr/">HomePage</url>
        </supervisor>
    </project-data>
    <workteam>
        <team-member>
            <name>Ricardo Silva</name>
            <number>84123</number>
            <email>a84123@alunos.uminho.pt</email>
            <url href="https://github.com/ricardoSlv">Github</url>
        </team-member>
    </workteam>
    <main-content>
        <abstract>
            <p>O trabalho de casa 3 correspondia à entrega de um ficheiro <url href="https://www.w3schools.com/xml/xml_dtd_intro.asp">Dtd</url> para validar um ficheiro <url href="https://www.w3schools.com/xml/xml_whatis.asp">Xml</url> fornecido e de um ficheiro <url href="https://www.w3schools.com/xml/xsl_intro.asp">Xslt</url> para gerar um website multi-página a partir do mesmo. </p>
            <p>O Website está dividido em 2 partes: <b>home-page</b>, <b>registos</b></p>
            <p>Através do Dtd pude que muitas das propriedades existentes para um registo não estão presentes em todos estes. Optei por por incluir apenas os obrigatórios no website com a exeção da informação cronológica.  </p>
            <p>É possivel navegar entre registos dentro do website, para criar esta fucionalidade usei os seletores: <i>following-sibling</i> e <i>preceding-sibling</i> de <b>Xpath</b> e gerei anchors para os ficheiros html correspondentes.</p>
            <p>Não consegui encontrar um solução para poder ordenar alfabeticamente os registos e ao mesmo tempo manter a navegação a funcionar</p>
            <p>Para melhorar a aparência do website decidi incluir o framework de css <url href="https://getbootstrap.com/">Bootstrap</url>.</p>
        </abstract>
    </main-content>
    <deliverables>
        <url href="https://github.com/ricardoSlv/DAW2020/blob/master/T3/arq.xml">arq.xml</url>
        <url href="https://github.com/ricardoSlv/DAW2020/blob/master/T3/arq.dtd">arq.dtd</url>
        <url href="https://github.com/ricardoSlv/DAW2020/blob/master/T3/arq.xsl">arq.xsl</url>
    </deliverables>
</project-record>

=== ricardoSlv/DAW2020/T2/project-record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "./project-record.dtd">
<project-record>
    <project-data>
        <keyname>DAW-TPC2-2020</keyname>
        <title>Desenvolvimento de um DTD para relatórios DAW</title>
        <subtitle>Relatório do trabalho de casa 2 da cadeira DAW 2020</subtitle>
        <begin-date>Outubro 2020</begin-date>
        <end-date>Outubro 2020</end-date>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <email>jcr@di.uminhp.pt</email>
            <url href="http://www3.di.uminho.pt/~jcr/">HomePage</url>
        </supervisor>
    </project-data>
    <workteam>
        <team-member>
            <name>Ricardo Silva</name>
            <number>84123</number>
            <email>a84123@alunos.uminho.pt</email>
            <url href="https://github.com/ricardoSlv">Github</url>
        </team-member>
    </workteam>
    <main-content>
        <abstract>
            <p>O trabalho de casa 2 correspondia à entrega de um ficheiro <url href="https://www.w3schools.com/xml/xml_dtd_intro.asp">Dtd</url> de acordo com as especificações fornecidas, e de um ficheiro xml como relatório que cumpra com esse mesmo Dtd. </p>
            <p>O documento está dividido em 4 partes: <b>project-data</b>,<b>workteam</b>,<b>main-content</b>,<b>deliverables</b></p>
            <p><b>Project-data</b> contém informações gerais sobre o projeto/tpc: Nome de código, titulo, subtitulo, data de inicio, data de fim e supervisor(<i>nome, email, pagina web</i>) </p>
            <p><b>WorkTeam</b> corresponde à descrição dos membros do grupo(<i>nome, numero, email, pagina web</i>) </p>
            <p><b>Main-content</b> corresponde ao corpo do documento, de momento apenas contem o abstract </p>
            <p><b>Deliverables</b> contém urls para os ficheros que compõem o projeto, neste caso, os ficheiros <b>project-record.dtd</b> e <b>project-record.xml</b> </p>
            <p> Este relatório foi validado e está de acordo com o Dtd definido.</p>
        </abstract>
    </main-content>
    <deliverables>
        <url href="https://github.com/ricardoSlv/DAW2020/blob/master/T2/project-record.dtd">project-record.dtd</url>
        <url href="https://github.com/ricardoSlv/DAW2020/blob/master/T2/project-record.xml">project-record.xml</url>
    </deliverables>
</project-record>
